apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sakswebsite
  title: Www.saksfifthavenue.com
  description: A static HTML website. Just like the good old days.
  links:
    - url: https://dhanu0001.github.io/sakswebsite/
      title: Live website
  annotations:
    github.com/project-slug: dhanu0001/sakswebsite
spec:
  type: website
  owner: engineering
  lifecycle: experimental
